[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/offsite-evaluate"
  to = "/.netlify/functions/offsite-evaluate"
  status = 200

[[redirects]]
  from = "/api/offsite-evaluate-suggestion"
  to = "/.netlify/functions/offsite-evaluate-suggestion"
  status = 200

[[redirects]]
  from = "/api/spacecat"
  to = "/.netlify/functions/spacecat"
  status = 200

[[redirects]]
  from = "/api/spacecat-config"
  to = "/.netlify/functions/spacecat-config"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
